spring:
  banner:
    location: classpath:/banner/banner.txt
  codec:
    max-in-memory-size: 50MB
feign:
  pokemon:
    name: pokemon
    url: https://pokeapi.co/api/v2
cache:
  timeout: 600000
---
application:
  title: Pockemon APP
  version: 0.0.1-SNAPSHOT
---
logging:
  level:
    root: INFO
    com.alea: DEBUG
    org.springframework.boot: INFO